import React from "react";
import About from "../components/About";
import MyComponets from "../components/MyComponets";
import ContactUs from "../components/ContactUs";
export const metadata = {
    title: " About Page",
    description: "Generated by create next app",
};
const page = () => {
    return ( <
        div > { " " } <
        MyComponets / > < About / >
        <
        ContactUs / >
        <
        /div>
    );
};

export default page;