import About from "./components/About";

import MyComponets from "./components/MyComponets";
export const metadata = {
    title: "Home Page",
    description: "Generated by create next app",
};
export default function Home() {
    return ( <
        >
        <
        div >
        <
        MyComponets / >
        <
        About / >
        <
        /div>{" "} <
        />
    );
}